### ISSUE TITLE
Installation fails for Node.js 13.6 due to outdated grpc dependency

### ISSUE THREAD

**Issue by florianb** [microsoft/etcd3#117]
The installation of grpc in the Node.js 13.6 fails with the attached error message. This is likely caused by an issue in grpc (compare [grpc/1086](https://github.com/grpc/grpc-node/issues/1086)) and should have been fixed for the release of 1.24.2.

### NPM install log

```
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.o
In file included from /usr/include/string.h:494,
                 from ../deps/grpc/third_party/nanopb/pb.h:68,
                 from ../deps/grpc/third_party/nanopb/pb_decode.h:9,
                 from ../deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc:21:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘grpc_grpclb_request* grpc_grpclb_request_create(const char*)’ at ../deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc:70:10:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 128 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [grpc.target.mk:501: Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.o] Fehler 1
make: Verzeichnis „/home/florian-breisch/github/etcd3/node_modules/grpc/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/florian-breisch/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-26-generic
gyp ERR! command "/home/florian-breisch/.nvm/versions/node/v13.6.0/bin/node" "/home/florian-breisch/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/florian-breisch/github/etcd3/node_modules/grpc/src/node/extension_binary/node-v79-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/florian-breisch/github/etcd3/node_modules/grpc/src/node/extension_binary/node-v79-linux-x64-glibc" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /home/florian-breisch/github/etcd3/node_modules/grpc
gyp ERR! node -v v13.6.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/florian-breisch/.nvm/versions/node/v13.6.0/bin/node /home/florian-breisch/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/florian-breisch/github/etcd3/node_modules/grpc/src/node/extension_binary/node-v79-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/florian-breisch/github/etcd3/node_modules/grpc/src/node/extension_binary/node-v79-linux-x64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/florian-breisch/github/etcd3/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 5.3.0-26-generic
node-pre-gyp ERR! command "/home/florian-breisch/.nvm/versions/node/v13.6.0/bin/node" "/home/florian-breisch/github/etcd3/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/florian-breisch/github/etcd3/node_modules/grpc
node-pre-gyp ERR! node -v v13.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/florian-breisch/.nvm/versions/node/v13.6.0/bin/node /home/florian-breisch/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/florian-breisch/github/etcd3/node_modules/grpc/src/node/extension_binary/node-v79-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/florian-breisch/github/etcd3/node_modules/grpc/src/node/extension_binary/node-v79-linux-x64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.21.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.21.1 install script.
```

**Comment by pauliusuza** [comment]
I'm proposing to switch to Typescript implementation of the official grpc library as it's production ready. Pull request can be found here: https://github.com/mixer/etcd3/pull/123

**Comment by florianb** [comment]
We published a fork with the bumped version - but i would probably not rely on since we don't use it in production hence it's not maintained with normal priority: https://www.npmjs.com/package/@mindkeeper-solutions/etcd3

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/etcd3/commit/6d67af2e247db35363a677ec7c83a780db4a8dda -- will be out later this week

**Comment by khaja-nizamuddin1** [comment]
I had same issue, uninstalled React native, expo and then Node js (latest version),
 downloaded and installed 12.13.0, following React Native and expo
and issue resolved!
