### ISSUE TITLE
etcdserver: permission denied

### ISSUE THREAD

**Issue by NeroCho** [microsoft/etcd3#124]
Sorry, my English is not very good. Here are my questions：

create user & role;
```
  const devRole = await client.role('devManager').create();
  await devRole.grant({
    permission: 'Readwrite',
    range: client.range({ prefix: '/' }),
  });

  const devUser = await client.user('winnerDev').create('123456');
  devUser.addRole(devRole);
```
login
```
new Etcd3({
      hosts: 'http://localhost:2379',
      auth: {
        username: 'winnerDev',
        password: '123456',
      }
    });
```
got error
```
(node:89633) UnhandledPromiseRejectionWarning: EtcdPermissionDeniedError: 7 PERMISSION_DENIED: etcdserver: permission denied
    at Object.exports.createStatusError (/Users/nerocho/Project/winner-libary/winner-config/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/nerocho/Project/winner-libary/winner-config/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/nerocho/Project/winner-libary/winner-config/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/nerocho/Project/winner-libary/winner-config/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/nerocho/Project/winner-libary/winner-config/node_modules/grpc/src/client_interceptors.js:847:24)
```
but use https://etcdmanager.io/ can login with `winnerDev`, can be used as well .

**Comment by connor4312** [comment]
etcdmanager uses this module, so it is probably some configuration or network issue on your end. I'm not able to reproduce this locally. If you're able to put together a standalone reproduction, that would be helpful in debugging. Ping me if so!
